import type { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
  title: "Black, Modern, Simple.",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Redirection automatique vers la locale française par défaut
  return children
}


